# Generated by Django 2.2.2 on 2019-11-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0018_auto_20191102_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('total_receipt', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_code', models.ForeignKey(db_column='customer_code', on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer')),
                ('payment_method_code', models.ForeignKey(db_column='payment_method_code', on_delete=django.db.models.deletion.CASCADE, to='receipt.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem', models.IntegerField()),
                ('amount_paid_here', models.FloatField(null=True)),
                ('invoice_no', models.ForeignKey(db_column='invoice_no', on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('receipt_no', models.ForeignKey(db_column='receipt_no', on_delete=django.db.models.deletion.CASCADE, to='receipt.Receipt')),
            ],
            options={
                'unique_together': {('lineitem', 'receipt_no')},
            },
        ),
    ]
