# Generated by Django 3.1.2 on 2020-10-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payment_method_code',
        ),
        migrations.AlterUniqueTogether(
            name='receiptlineitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='receiptlineitem',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='receiptlineitem',
            name='receipt_no',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptLineItem',
        ),
    ]
