# Generated by Django 3.1.2 on 2020-10-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'managed': False},
        ),
    ]
