# Generated by Django 2.2.2 on 2019-10-31 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('credit_limit', models.FloatField(blank=True)),
                ('country', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('units', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('invoice_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True)),
                ('unit_price', models.FloatField(blank=True)),
                ('extended_price', models.FloatField(blank=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('due_date', models.DateField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('vat', models.FloatField(blank=True)),
                ('amount_due', models.FloatField(blank=True)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer')),
            ],
        ),
    ]
