# Generated by Django 2.2.2 on 2019-11-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20191101_0527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceLineItem',
        ),
    ]
