# Generated by Django 2.2.2 on 2019-11-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_delete_invoicelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem', models.IntegerField()),
                ('invoice_no', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.FloatField(null=True)),
                ('extended_price', models.FloatField(null=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Product')),
            ],
            options={
                'unique_together': {('lineitem', 'invoice_no')},
            },
        ),
    ]
