# Generated by Django 2.2.2 on 2019-11-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20191101_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('units', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Product'),
        ),
    ]
