# Generated by Django 2.2.2 on 2019-11-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20191101_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoice.Product'),
        ),
    ]
