# Generated by Django 2.2.2 on 2019-11-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20191102_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_code',
            field=models.ForeignKey(db_column='customer_code', on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product_code',
            field=models.ForeignKey(db_column='product_code', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='invoice.Product'),
        ),
    ]
