# Generated by Django 2.2.2 on 2019-11-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20191102_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice_no',
            field=models.ForeignKey(db_column='invoice_no', on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice'),
        ),
    ]
